export interface TriviaQuestion {
  id: number;
  question: string;
  options: string[];
  correct: number;
  category: string;
}

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  // Historia española
  {
    id: 1,
    question: '¿Cuántos años duró la dictadura de Francisco Franco en España?',
    options: ['20 años', '36 años', '46 años', '28 años'],
    correct: 1,
    category: 'Historia española',
  },
  {
    id: 2,
    question: '¿En qué año se aprobó la Constitución española que marcó el fin oficial de la dictadura?',
    options: ['1975', '1977', '1978', '1982'],
    correct: 2,
    category: 'Historia española',
  },
  {
    id: 3,
    question: '¿Qué partido / movimiento gobernó España durante la dictadura franquista?',
    options: ['PSOE', 'Falange / Movimiento Nacional', 'Partido Popular', 'UCD'],
    correct: 1,
    category: 'Historia española',
  },
  {
    id: 4,
    question: '¿En qué año España legalizó el matrimonio entre personas del mismo sexo?',
    options: ['2003', '2005', '2007', '2010'],
    correct: 1,
    category: 'Historia española',
  },
  {
    id: 5,
    question: '¿En qué año España aprobó su primera ley del aborto?',
    options: ['1982', '1985', '1990', '1995'],
    correct: 1,
    category: 'Historia española',
  },
  {
    id: 6,
    question: '¿Cuántos escaños tiene el Congreso de los Diputados español?',
    options: ['300', '350', '400', '250'],
    correct: 1,
    category: 'Historia española',
  },
  {
    id: 7,
    question: '¿En qué año España ingresó en la Comunidad Económica Europea?',
    options: ['1978', '1982', '1986', '1992'],
    correct: 2,
    category: 'Historia española',
  },
  {
    id: 8,
    question: '¿Quién fue el primer presidente del Gobierno en la democracia española actual?',
    options: ['Felipe González', 'Adolfo Suárez', 'Leopoldo Calvo-Sotelo', 'Santiago Carrillo'],
    correct: 1,
    category: 'Historia española',
  },
  {
    id: 9,
    question: '¿En qué año fue fundado el PSOE?',
    options: ['1879', '1920', '1931', '1945'],
    correct: 0,
    category: 'Historia española',
  },
  {
    id: 10,
    question: '¿Cuál fue el resultado del referéndum catalán del 1-O (2017) entre quienes votaron?',
    options: ['Sí a la independencia con más del 90%', 'Sí ganó con ~60%', 'No ganó ajustado', 'Empate técnico'],
    correct: 0,
    category: 'Historia española',
  },

  // Historia mundial
  {
    id: 11,
    question: '¿En qué año cayó el Muro de Berlín?',
    options: ['1987', '1989', '1991', '1993'],
    correct: 1,
    category: 'Historia mundial',
  },
  {
    id: 12,
    question: '¿En qué año se disolvió la Unión Soviética?',
    options: ['1989', '1990', '1991', '1992'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 13,
    question: '¿Qué presidente de EEUU ordenó lanzar las bombas atómicas sobre Japón en 1945?',
    options: ['Franklin Roosevelt', 'Dwight Eisenhower', 'Harry Truman', 'Richard Nixon'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 14,
    question: '¿En qué país nació el fascismo como ideología política?',
    options: ['Alemania', 'España', 'Italia', 'Austria'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 15,
    question: '¿Cuántas personas murieron aproximadamente en el Holocausto judío según los historiadores?',
    options: ['600.000', '2 millones', '6 millones', '15 millones'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 16,
    question: '¿Cuántos años estuvo Nelson Mandela en prisión?',
    options: ['18 años', '27 años', '35 años', '12 años'],
    correct: 1,
    category: 'Historia mundial',
  },
  {
    id: 17,
    question: '¿Qué país fue el primero del mundo en conceder el voto a la mujer?',
    options: ['Reino Unido', 'Estados Unidos', 'Nueva Zelanda', 'Francia'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 18,
    question: '¿Cuál fue el primer país del mundo en legalizar el aborto?',
    options: ['Suecia', 'Francia', 'La Unión Soviética', 'Dinamarca'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 19,
    question: '¿Cuál fue el primer país del mundo en legalizar el matrimonio homosexual?',
    options: ['Suecia', 'Países Bajos', 'Bélgica', 'Canadá'],
    correct: 1,
    category: 'Historia mundial',
  },
  {
    id: 20,
    question: '¿Cuántas guerras ha declarado formalmente el Congreso de EEUU desde 1945?',
    options: ['Ninguna (0 declaraciones formales)', '5', '10', '15'],
    correct: 0,
    category: 'Historia mundial',
  },
  {
    id: 21,
    question: '¿Cuántos presidentes de EEUU han sido asesinados mientras ejercían el cargo?',
    options: ['1', '2', '4', '6'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 22,
    question: '¿En qué año se produjo la Revolución Cubana liderada por Fidel Castro?',
    options: ['1953', '1956', '1959', '1962'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 23,
    question: '¿En qué año la URSS lanzó el Sputnik, el primer satélite artificial de la historia?',
    options: ['1955', '1957', '1961', '1963'],
    correct: 1,
    category: 'Historia mundial',
  },

  // Política internacional
  {
    id: 24,
    question: '¿Cuántos países integran actualmente la Unión Europea?',
    options: ['25', '27', '29', '31'],
    correct: 1,
    category: 'Política internacional',
  },
  {
    id: 25,
    question: '¿Cuántos miembros permanentes con derecho a veto tiene el Consejo de Seguridad de la ONU?',
    options: ['3', '5', '7', '10'],
    correct: 1,
    category: 'Política internacional',
  },
  {
    id: 26,
    question: '¿Cuántos estados miembros tiene la ONU actualmente?',
    options: ['150', '170', '193', '210'],
    correct: 2,
    category: 'Política internacional',
  },
  {
    id: 27,
    question: '¿Qué país posee el mayor arsenal nuclear del mundo?',
    options: ['Estados Unidos', 'Rusia', 'China', 'Francia'],
    correct: 1,
    category: 'Política internacional',
  },
  {
    id: 28,
    question: '¿Qué país gasta más en armamento militar en el mundo?',
    options: ['China', 'Rusia', 'Estados Unidos', 'Arabia Saudí'],
    correct: 2,
    category: 'Política internacional',
  },
  {
    id: 29,
    question: '¿Cuál es el mayor exportador de armas del mundo?',
    options: ['Rusia', 'Francia', 'Estados Unidos', 'China'],
    correct: 2,
    category: 'Política internacional',
  },
  {
    id: 30,
    question: '¿En qué año fue fundada la OTAN?',
    options: ['1945', '1949', '1955', '1961'],
    correct: 1,
    category: 'Política internacional',
  },
  {
    id: 31,
    question: '¿Cuál de estos países NO es miembro de la OTAN?',
    options: ['España', 'Turquía', 'Suiza', 'Polonia'],
    correct: 2,
    category: 'Política internacional',
  },
  {
    id: 32,
    question: '¿Cuántos refugiados había en el mundo en 2023 según ACNUR?',
    options: ['30 millones', '60 millones', '110 millones', '250 millones'],
    correct: 2,
    category: 'Política internacional',
  },
  {
    id: 33,
    question: '¿Cuántos países forman el G-20?',
    options: ['15 países', '19 países + UE', '25 países', '30 países'],
    correct: 1,
    category: 'Política internacional',
  },

  // Economía y sociedad
  {
    id: 34,
    question: '¿Cuántos mandatos presidenciales puede cumplir como máximo un presidente de EEUU?',
    options: ['Ilimitados', '2 mandatos', '3 mandatos', '1 mandato'],
    correct: 1,
    category: 'Economía y sociedad',
  },
  {
    id: 35,
    question: '¿Cuántos artículos tiene la Constitución Española de 1978?',
    options: ['100', '169', '200', '252'],
    correct: 1,
    category: 'Economía y sociedad',
  },
  {
    id: 36,
    question: '¿En qué año se firmó la Declaración Universal de los Derechos Humanos?',
    options: ['1945', '1948', '1950', '1955'],
    correct: 1,
    category: 'Economía y sociedad',
  },
  {
    id: 37,
    question: '¿Cuántas personas viven actualmente en China?',
    options: ['800 millones', '1.000 millones', '1.400 millones', '2.000 millones'],
    correct: 2,
    category: 'Economía y sociedad',
  },
  {
    id: 38,
    question: '¿En qué año se firmó el Acuerdo de París sobre el cambio climático?',
    options: ['2010', '2013', '2015', '2018'],
    correct: 2,
    category: 'Economía y sociedad',
  },
  {
    id: 39,
    question: '¿Cuántas personas mueren al año en el mundo por causas relacionadas con el tabaco?',
    options: ['1 millón', '3 millones', '8 millones', '15 millones'],
    correct: 2,
    category: 'Economía y sociedad',
  },
  {
    id: 40,
    question: '¿Qué porcentaje de la riqueza mundial posee aproximadamente el 1% más rico?',
    options: ['Más del 10%', 'Más del 25%', 'Más del 43%', 'Más del 70%'],
    correct: 2,
    category: 'Economía y sociedad',
  },
  {
    id: 41,
    question: '¿En qué año fue fundada la Organización de las Naciones Unidas?',
    options: ['1943', '1945', '1947', '1950'],
    correct: 1,
    category: 'Economía y sociedad',
  },
  {
    id: 42,
    question: '¿Cuál es el país con mayor número de presos del mundo en cifras absolutas?',
    options: ['Rusia', 'China', 'Estados Unidos', 'Brasil'],
    correct: 2,
    category: 'Economía y sociedad',
  },
  {
    id: 43,
    question: '¿Cuántos mandatos presidenciales puede tener un presidente en México?',
    options: ['Ilimitados', '2 mandatos', 'Solo 1, sin reelección', '3 mandatos'],
    correct: 2,
    category: 'Economía y sociedad',
  },
  {
    id: 44,
    question: '¿En qué país hay más billonarios del mundo en términos absolutos?',
    options: ['China', 'India', 'Estados Unidos', 'Arabia Saudí'],
    correct: 2,
    category: 'Economía y sociedad',
  },
  {
    id: 45,
    question: '¿Qué sistema económico defiende la propiedad privada de los medios de producción y el libre mercado?',
    options: ['Socialismo', 'Comunismo', 'Capitalismo', 'Anarquismo'],
    correct: 2,
    category: 'Economía y sociedad',
  },
  {
    id: 46,
    question: '¿Quién fue el primer Secretario General de la ONU?',
    options: ['Dag Hammarskjöld', 'Kofi Annan', 'Trygve Lie', 'U Thant'],
    correct: 2,
    category: 'Política internacional',
  },
  {
    id: 47,
    question: '¿Cuántos países han tenido a una mujer como jefa de gobierno o estado hasta 2024?',
    options: ['Menos de 10', 'Entre 20 y 30', 'Más de 60', 'Todos los países del mundo'],
    correct: 2,
    category: 'Economía y sociedad',
  },
  {
    id: 48,
    question: '¿En qué año se firmó el Tratado de Maastricht que creó la Unión Europea?',
    options: ['1989', '1992', '1995', '1998'],
    correct: 1,
    category: 'Política internacional',
  },
  {
    id: 49,
    question: '¿Cuántos países tienen pena de muerte en su legislación actualmente?',
    options: ['Menos de 20', 'Alrededor de 55', 'Más de 120', 'Todos menos uno'],
    correct: 1,
    category: 'Política internacional',
  },
  {
    id: 50,
    question: '¿Cuál es el país europeo con el impuesto marginal más alto a las rentas altas?',
    options: ['Alemania', 'Francia', 'Suecia', 'Dinamarca'],
    correct: 3,
    category: 'Economía y sociedad',
  },

  // Asesinato de Kennedy
  {
    id: 51,
    question: '¿En qué ciudad fue asesinado el presidente John F. Kennedy?',
    options: ['Washington D.C.', 'Chicago', 'Dallas, Texas', 'Houston, Texas'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 52,
    question: '¿Quién fue declarado único asesino de JFK según la Comisión Warren?',
    options: ['Jack Ruby', 'Lee Harvey Oswald', 'James Earl Ray', 'Sirhan Sirhan'],
    correct: 1,
    category: 'Historia mundial',
  },
  {
    id: 53,
    question: '¿Desde qué edificio disparó el asesino de Kennedy según la investigación oficial?',
    options: ['Dal-Tex Building', 'Texas School Book Depository', 'Hotel Texas', 'Union Terminal'],
    correct: 1,
    category: 'Historia mundial',
  },
  {
    id: 54,
    question: '¿Quién mató a Lee Harvey Oswald antes de que pudiera ser juzgado?',
    options: ['Un agente de la CIA', 'Un policía de Dallas', 'Jack Ruby', 'Un cómplice desconocido'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 55,
    question: '¿Cómo se llamó la comisión oficial que investigó el asesinato de JFK?',
    options: ['Comisión Church', 'Comisión Warren', 'Comisión Pike', 'Comisión Rockefeller'],
    correct: 1,
    category: 'Historia mundial',
  },
  {
    id: 56,
    question: 'Lee Harvey Oswald, acusado del asesinato de JFK, había desertado previamente a la Unión Soviética. ¿Qué ideología se le atribuía?',
    options: ['Ultraderechista', 'Anarquista', 'Marxista', 'Nacionalista'],
    correct: 2,
    category: 'Historia mundial',
  },

  // Atentados del 11-S
  {
    id: 57,
    question: '¿Cuántos secuestradores participaron en los atentados del 11 de septiembre de 2001?',
    options: ['9', '15', '19', '23'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 58,
    question: '¿Cuántos aviones fueron secuestrados el 11-S?',
    options: ['2', '3', '4', '5'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 59,
    question: '¿Dónde se estrelló el cuarto avión del 11-S, el que no alcanzó su objetivo?',
    options: ['Camp David (Maryland)', 'Shanksville (Pensilvania)', 'Pittsburgh (Pensilvania)', 'Frederick (Maryland)'],
    correct: 1,
    category: 'Historia mundial',
  },
  {
    id: 60,
    question: '¿Cuántas personas murieron aproximadamente en los atentados del 11-S?',
    options: ['Unas 800', 'Unas 1.500', 'Casi 3.000', 'Más de 5.000'],
    correct: 2,
    category: 'Historia mundial',
  },
  {
    id: 61,
    question: '¿Qué organización terrorista perpetró los atentados del 11-S?',
    options: ['Estado Islámico (ISIS)', 'Al-Qaeda', 'Hamás', 'Mossad'],
    correct: 3,
    category: 'Historia mundial',
  },
  {
    id: 62,
    question: '¿Cuál fue la nacionalidad mayoritaria de los 19 secuestradores del 11-S?',
    options: ['Iraní', 'Afgana', 'Egipcia', 'Saudí'],
    correct: 3,
    category: 'Historia mundial',
  },

  // Escándalos políticos españoles
  {
    id: 63,
    question: '¿De qué ministerio era titular José Luis Ábalos cuando estalló el caso Koldo?',
    options: ['Ministerio del Interior', 'Ministerio de Transportes', 'Ministerio de Economía', 'Ministerio de Justicia'],
    correct: 1,
    category: 'Escándalos políticos',
  },
  {
    id: 64,
    question: '¿Sobre qué contratos giraba la presunta corrupción del caso Koldo?',
    options: ['Contratos de obra pública en AVE', 'Mascarillas COVID-19', 'Contratos de energía renovable', 'Contratos militares'],
    correct: 1,
    category: 'Escándalos políticos',
  },
  {
    id: 65,
    question: '¿Quién era el asesor de Ábalos implicado en el caso Koldo que le da nombre?',
    options: ['Santos Cerdán', 'Koldo García', 'Víctor de Aldama', 'Francisco Salazar'],
    correct: 1,
    category: 'Escándalos políticos',
  },
  {
    id: 66,
    question: '¿En qué mes y año se produjeron las primeras detenciones del caso Koldo?',
    options: ['Junio de 2023', 'Octubre de 2023', 'Febrero de 2024', 'Septiembre de 2024'],
    correct: 2,
    category: 'Escándalos políticos',
  },
  {
    id: 67,
    question: '¿Quién es Begoña Gómez en relación con la política española?',
    options: ['Ministra de Igualdad', 'Esposa del presidente Pedro Sánchez', 'Secretaria General del PSOE', 'Presidenta de la Comunidad de Madrid'],
    correct: 1,
    category: 'Escándalos políticos',
  },
  {
    id: 68,
    question: '¿Cuál es el principal delito investigado en el caso Begoña Gómez?',
    options: ['Fraude fiscal', 'Tráfico de influencias', 'Malversación de fondos', 'Blanqueo de capitales'],
    correct: 1,
    category: 'Escándalos políticos',
  },
  {
    id: 69,
    question: '¿Qué asociación presentó la denuncia que originó el caso Begoña Gómez?',
    options: ['Ciudadanos en Acción', 'Manos Limpias', 'Hazte Oír', 'Vox Legal'],
    correct: 1,
    category: 'Escándalos políticos',
  },
  {
    id: 70,
    question: '¿Con qué régimen latinoamericano se relacionan las investigaciones sobre el expresidente Zapatero?',
    options: ['Cuba (Díaz-Canel)', 'Nicaragua (Ortega)', 'Venezuela (Maduro)', 'Bolivia (Arce)'],
    correct: 2,
    category: 'Escándalos políticos',
  },
  {
    id: 71,
    question: '¿Qué aerolínea española recibió un rescate estatal de 53 millones vinculado a accionistas venezolanos en el caso Zapatero?',
    options: ['Air Europa', 'Vueling', 'Plus Ultra', 'Iberia Express'],
    correct: 2,
    category: 'Escándalos políticos',
  },

  // Franco
  {
    id: 72,
    question: '¿En qué año se creó el Seguro Obligatorio de Enfermedad (SOE), el primer sistema de sanidad pública de España, bajo el franquismo?',
    options: ['1936', '1942', '1950', '1960'],
    correct: 1,
    category: 'Franco',
  },
  {
    id: 73,
    question: '¿Cómo se llamó el período de rápido crecimiento económico español de los años 60 bajo Franco?',
    options: ['La Restauración', 'El Desarrollismo', 'El Milagro', 'La Autarquía'],
    correct: 1,
    category: 'Franco',
  },
  {
    id: 74,
    question: '¿Qué porcentaje de la población española era analfabeta al inicio del franquismo (1940) frente al final (1975)?',
    options: ['Pasó del 50% al 10%', 'Pasó del 23% al 9%', 'No cambió significativamente', 'Aumentó por la guerra'],
    correct: 1,
    category: 'Franco',
  },
  {
    id: 75,
    question: '¿Qué plan económico franquista de 1959 abrió España al exterior y acabó con la autarquía?',
    options: ['Plan Marshall español', 'Plan de Estabilización', 'Plan de Desarrollo', 'Plan de Urgencia Social'],
    correct: 1,
    category: 'Franco',
  },
  {
    id: 76,
    question: '¿Cuántas personas fueron ejecutadas por el régimen franquista según estimaciones históricas tras la Guerra Civil?',
    options: ['Menos de 1.000', 'Entre 3.000 y 5.000', 'Entre 20.000 y 50.000', 'Más de 200.000'],
    correct: 2,
    category: 'Franco',
  },
  {
    id: 77,
    question: '¿Qué organismo franquista construyó más de 500.000 viviendas sociales entre 1939 y 1975?',
    options: ['El INI', 'El Banco de España', 'El Instituto Nacional de la Vivienda', 'La Caja de Ahorros'],
    correct: 2,
    category: 'Franco',
  },
  {
    id: 78,
    question: '¿Cuánto creció el PIB per cápita español durante el desarrollismo franquista (1960-1975)?',
    options: ['Se duplicó', 'Se triplicó', 'Creció un 10%', 'Disminuyó por las sanciones'],
    correct: 0,
    category: 'Franco',
  },
  {
    id: 79,
    question: '¿Cuántos españoles emigraron al extranjero como mano de obra durante el desarrollismo franquista (años 60)?',
    options: ['Unos 50.000', 'Unos 200.000', 'Más de 1 millón', 'Más de 3 millones'],
    correct: 2,
    category: 'Franco',
  },
  {
    id: 80,
    question: '¿En qué año fue ejecutado por garrote vil el último condenado a muerte del franquismo, generando protestas internacionales?',
    options: ['1968', '1972', '1975', '1977'],
    correct: 2,
    category: 'Franco',
  },

  // Hitler
  {
    id: 81,
    question: '¿En qué país nació Adolf Hitler?',
    options: ['Alemania', 'Austria', 'Suiza', 'Polonia'],
    correct: 1,
    category: 'Hitler',
  },
  {
    id: 82,
    question: '¿En qué año llegó Hitler al poder como Canciller de Alemania?',
    options: ['1929', '1931', '1933', '1935'],
    correct: 2,
    category: 'Hitler',
  },
  {
    id: 83,
    question: '¿Cómo se llamaba el partido de Hitler?',
    options: ['Partido Fascista Alemán', 'Partido Nacional Socialista Obrero Alemán (NSDAP)', 'Partido Comunista Alemán', 'Partido Imperial Alemán'],
    correct: 1,
    category: 'Hitler',
  },
  {
    id: 84,
    question: '¿En qué fecha comenzó la Segunda Guerra Mundial con la invasión nazi de Polonia?',
    options: ['1 de septiembre de 1939', '1 de enero de 1939', '3 de septiembre de 1939', '1 de mayo de 1940'],
    correct: 0,
    category: 'Hitler',
  },
  {
    id: 85,
    question: '¿Cuándo murió Adolf Hitler?',
    options: ['8 de mayo de 1945 (rendición alemana)', '30 de abril de 1945 (suicidio en Berlín)', '12 de abril de 1945 (ejecutado)', '1 de mayo de 1945 (batalla de Berlín)'],
    correct: 1,
    category: 'Hitler',
  },
  {
    id: 86,
    question: '¿En qué año escribió Hitler "Mein Kampf", su manifiesto ideológico?',
    options: ['1919', '1923-1924 (en prisión)', '1929', '1933'],
    correct: 1,
    category: 'Hitler',
  },
  {
    id: 87,
    question: '¿Cómo se llamó el pogrom nazi de noviembre de 1938 en que destruyeron sinagogas y negocios judíos?',
    options: ['Noche de los Cuchillos Largos', 'Noche de los Cristales Rotos', 'Operación Reinhard', 'Noche de las Antorchas'],
    correct: 1,
    category: 'Hitler',
  },
  {
    id: 88,
    question: '¿Cuántos judíos fueron asesinados en el Holocausto nazi según el consenso histórico?',
    options: ['Unos 271.000', 'Unos 2 millones', 'Unos 6 millones', 'Más de 10 millones'],
    correct: 0,
    category: 'Hitler',
  },
  {
    id: 89,
    question: '¿Cómo se llamó la invasión alemana de la Unión Soviética en 1941?',
    options: ['Operación Dynamo', 'Operación Sealion', 'Operación Barbarroja', 'Operación Valkiria'],
    correct: 2,
    category: 'Hitler',
  },
  {
    id: 90,
    question: '¿Cuántos soldados soviéticos y civiles murió la URSS aproximadamente en la Segunda Guerra Mundial?',
    options: ['500.000', '2 millones', '10 millones', '27 millones'],
    correct: 3,
    category: 'Hitler',
  },
];
